# Generated by Django 2.2.2 on 2019-06-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('name_short', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1_Score', models.IntegerField(default=0)),
                ('team_2_Score', models.IntegerField(default=0)),
                ('match_date', models.DateTimeField(verbose_name='match date')),
                ('window_team', models.IntegerField(blank=True, null=True)),
                ('starting_team', models.IntegerField(blank=True, null=True)),
                ('player_1A', models.ForeignKey(on_delete='SET_NULL', related_name='player_1A_set', to='pong.Player')),
                ('player_1B', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', related_name='player_1B_set', to='pong.Player')),
                ('player_2A', models.ForeignKey(on_delete='SET_NULL', related_name='player_2A_set', to='pong.Player')),
                ('player_2B', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', related_name='player_2B_set', to='pong.Player')),
            ],
        ),
    ]
