# Generated by Django 2.2.2 on 2019-07-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_1_Score',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2_Score',
            field=models.IntegerField(default=21),
        ),
    ]
