# Generated by Django 2.2.2 on 2019-07-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_auto_20190720_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='window_team',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
